### ISSUE TITLE
Bloomsky issues

### ISSUE THREAD

**Issue by blampen** [tfatykhov/WinkRedNode#45]
The camera snapshot is zoomed in and missing a large portion of the image that is saved. 

Also adding the api key through the ui would not save for me. I had to manually add it to blue mix-settings.

**Comment by tfatykhov** [comment]
Hi. Yes camera images on the screen are cropped but it still saves full image. I will address this later since it happens for all cameras. Regarding api key - I am not able to reproduce this. I deleted it from ui and re added and it works. Make sure you have latest flows imported for integration tab.

**Comment by tfatykhov** [comment]
fixed image cropping.
